ALTER TABLE `blog_post` ADD FOREIGN KEY (`blog_category_id`) REFERENCES `blog_category`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `blog_post` ADD FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `blog_category` ADD FOREIGN KEY (`parent`) REFERENCES `blog_category`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;