ALTER TABLE `files` ADD FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `files` ADD FOREIGN KEY (`category`) REFERENCES `files_category`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;
